version: 2

jobs:
    build:
        environment:
            TZ: "/usr/share/zoneinfo/America/Detroit"
        working_directory: ~/app
        docker:
            # We are using this image because:
            # - It has Python preinstalled, which we need to do anything useful.
            # - It's Debian Jessie, which avoids "libssl-dev" being too new for
            # the versions of Python we want to test/support. (Debian Stretch
            # exhibits this problem and makes it impossible to test all 3.x
            # variants in a single tox execution. See
            # https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib
            # for details regarding "libssl-dev" vs "libssl1.0-dev".)
            # - It has Node, for our DevOps integrations.
            - image: circleci/python:3.6.6-jessie-node-browsers
            # This is used for benchmark tests.
            - image: erlio/docker-vernemq:1.3.1
              name: mqtt
              environment:
                DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'

        steps:
            ##
            # SETUP
            ##
            - run:
                name: Flag local/PR builds
                command: |
                  if [[ "$CIRCLE_BUILD_NUM" == '' ]]; then
                    touch ~/.localCircleBuild
                  fi
                  if [[ "$CIRCLE_PR_USERNAME" != '' ]]; then
                    touch ~/.prCircleBuild
                  fi
            - add_ssh_keys
            - checkout
            - run:
                name: Install jq
                command: |
                  sudo curl -sSL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
                  sudo chmod +x /usr/local/bin/jq
            - run:
                name: Calculate codebase version
                command: |
                  bash .devops/calculate-app-version.sh
                  bash .devops/semverTo440.sh
                  sed -i -e "s/__version__ = .*/__version__ = '$(cat ~/.version440)'/" auklet/__about__.py
                  VERSION_SIMPLE=$(cat ~/.version | xargs | cut -f1 -d"+")
                  sed -i -e "s/__semver__ = .*/__semver__ = '$VERSION_SIMPLE'/" auklet/__about__.py

            ##
            # RESTORE CACHES
            ##
            - restore_cache:
                key: v1-whitesource-cache-{{ checksum "requirements.txt" }}
            - restore_cache:
                key: v1-pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}
            - run:
                name: Ensure caches exist
                command: |
                  mkdir -p ~/.cache/pip ~/.whitesource-pip

            ##
            # TESTS
            ##
            - run:
                name: Install Python dependencies
                command: |
                  # https://github.com/pyenv/pyenv/wiki/Common-build-problems#requirements
                  sudo apt-get -y install \
                    make \
                    build-essential \
                    zlib1g-dev \
                    libbz2-dev \
                    libreadline-dev \
                    libsqlite3-dev \
                    wget \
                    curl \
                    llvm \
                    libncurses5-dev \
                    libncursesw5-dev \
                    xz-utils \
                    tk-dev \
                    libffi-dev \
                    liblzma-dev
                  # We need to use OpenSSL 1.0.2 to support all 3.x variants,
                  # and that version is only available in Jessie Backports.
                  # We'll also upgrade OpenSSL, just for good measure.
                  echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
                  sudo apt-get update
                  sudo apt-get -y -t jessie-backports install openssl libssl-dev
            - run:
                name: Run Unit Tests
                command: |
                  if [[ -f ~/.localCircleBuild ]]; then
                    CIRCLE_LOCAL_BUILD=true
                  else
                    CIRCLE_LOCAL_BUILD=false
                  fi
                  bash .devops/test_and_coverage.sh $CIRCLE_LOCAL_BUILD
            - store_artifacts:
                 path: ~/app/htmlcov
            - run:
                name: Run benchmark tests
                command: |
                  export PYTHONUNBUFFERED=0
                  mkdir .auklet
                  sudo python3 setup.py install
                  python3 src/benchmark/run_tests.py
            - run:
                name: Run Whitesource
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild && ! -f ~/.prCircleBuild ]]; then
                    bash .devops/whitesource.sh
                  fi

            ##
            # SAVE CACHES
            ##
            - save_cache:
                key: v1-whitesource-cache-{{ checksum "requirements.txt" }}
                paths:
                    - /home/circleci/.whitesource-pip
            - save_cache:
                key: v1-pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}
                paths:
                    - /home/circleci/.cache/pip

            ##
            # DEPLOYMENT
            ##
            - run:
                name: Deploy Beta (master)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      bash .devops/deploy.sh beta
                    fi
                  fi
            - run:
                name: Deploy RC (rc)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "rc" ]; then
                      bash .devops/deploy.sh rc
                      bash .devops/post-release.sh
                      # Need to checkout rc again so we can run more scripts.
                      git checkout rc
                      bash .devops/updateProdReleasePr.sh
                    fi
                  fi
            - run:
                name: Deploy Production (release)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "release" ]; then
                      bash .devops/deploy.sh release
                      bash .devops/post-release.sh
                    fi
                  fi
